# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f650a331fe3be27b291d8df5a178ad2fd6f28f31ae03b630631958d47611b6dbff72745bb90ad51124b98411f0bd2579c3428a47b06ceb00f5309c2f9df49a4b

test:
  secret_key_base: c82f79b2ff5ccc06b1b39650588917bd6f1aa9c746f7f35e8da6162df421f52068e68e6e975b418a1e5021a46b15e123c146e1b98b0e302a1627e8850eb18ff5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
